import { CompanyProfile, BPMProcess } from './types';

export interface PredefinedExample {
  id: string;
  name: string;
  description: string;
  company: CompanyProfile;
  processes: BPMProcess[];
}

export const EXAMPLES: PredefinedExample[] = [
  {
    id: 'portfolio-university',
    name: 'Educación Superior',
    description: 'Institución académica dedicada a la formación universitaria, docencia e investigación.',
    company: {
      name: 'Higher Education Academy',
      industry: 'Educación Superior',
      description: 'Institución académica dedicada a la formación universitaria, docencia e investigación.'
    },
    processes: [
      {
        id: '1',
        name: 'Schedule Courses',
        category: 'core',
        groupName: 'Operaciones Académicas',
        health: 2,
        importance: 5,
        feasibility: 3,
        labelPosition: 'left',
        visible: true,
        profile: {
          apqcCode: '3.1.1',
          vision: 'Asegurar una programación académica balanceada y optimizada para docentes, aulas y estudiantes cada semestre.',
          processOwner: 'Vicerrectoría Académica / Registro',
          customer: 'Docentes y Estudiantes matriculados',
          customerExpectation: 'Horarios sin cruces de clases, aulas adecuadas y publicación oportuna.',
          outcome: 'Calendario y programación horaria oficial publicada y aulas reservadas.',
          trigger: 'Apertura del ciclo de planificación académica del periodo lectivo.',
          firstActivity: 'Recopilar oferta académica y disponibilidad docente.',
          lastActivity: 'Publicar horarios consolidados en el portal académico.',
          interfacesInbound: 'Planificación Estratégica Institucional',
          interfacesOutbound: 'Matrícula e Inscripción de Asignaturas',
          requiredResourcesHuman: 'Coordinadores de programa, jefes de departamento, personal de registro.',
          requiredResourcesInfo: 'Mallas curriculares, capacidad de aulas, historial de matrícula.',
          requiredResourcesEnv: 'Sistema de Información Estudiantil (SIS) y software de optimización horaria.',
          performanceMeasures: 'Tasa de cruces de horarios\n% de utilización de aulas\nTiempo de ciclo de publicación'
        },
        profileEn: {
          apqcCode: '3.1.1',
          vision: 'Ensure a balanced and optimized academic schedule for faculty, classrooms, and students each semester.',
          processOwner: 'Academic Vice-Presidency / Registrar Office',
          customer: 'Faculty members and enrolled students',
          customerExpectation: 'Conflict-free schedules, suitable room allocation, and timely publication.',
          outcome: 'Official course schedule published and classrooms reserved.',
          trigger: 'Start of academic planning cycle for upcoming semester.',
          firstActivity: 'Collect course offerings and faculty availability.',
          lastActivity: 'Publish consolidated timetable on student portal.',
          interfacesInbound: 'Institutional Strategic Planning',
          interfacesOutbound: 'Course Registration & Enrollment',
          requiredResourcesHuman: 'Program coordinators, department chairs, registrar staff.',
          requiredResourcesInfo: 'Curricula, room capacities, historical enrollment data.',
          requiredResourcesEnv: 'Student Information System (SIS) and timetable scheduling software.',
          performanceMeasures: 'Schedule conflict rate\nRoom capacity utilization %\nTimetable publication cycle time'
        }
      },
      { id: '2', name: 'Manage Student Services', category: 'core', groupName: 'Operaciones Académicas', health: 3, importance: 4, feasibility: 3, labelPosition: 'left', visible: true },
      { id: '3', name: 'Develop and Manage Study Programs', category: 'management', health: 4, importance: 4, feasibility: 3, labelPosition: 'left', visible: true },
      { id: '4', name: 'Market Study Programs', category: 'management', health: 4, importance: 4, feasibility: 4, labelPosition: 'bottom', visible: true },
      { id: '5', name: 'Deliver Courses', category: 'core', groupName: 'Operaciones Académicas', health: 5, importance: 3, feasibility: 1, labelPosition: 'bottom', visible: true },
      { id: '6', name: 'Manage Facilities', category: 'support', health: 2, importance: 2, feasibility: 4, labelPosition: 'bottom', visible: true },
    ]
  },
  {
    id: 'dumas-sencillo',
    name: 'Retail y Distribución',
    description: 'Cadena de valor estándar de manufactura y ventas comerciales.',
    company: {
      name: 'Global Retail & Logistics Corp',
      industry: 'Comercio y Manufactura',
      description: 'Empresa de desarrollo, venta y entrega de bienes comerciales.'
    },
    processes: [
      { id: 'm1', name: 'Define, Operationalize, and Track Strategy', category: 'management', health: 4, importance: 5, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'm2', name: 'Sales, Franchise, and Partner Management', category: 'management', health: 3, importance: 4, feasibility: 3, labelPosition: 'right', visible: true },
      { id: 'c1', name: 'Innovate', category: 'core', groupName: 'Cadena Principal', sequenceOrder: 1, health: 3, importance: 5, feasibility: 3, labelPosition: 'left', visible: true },
      {
        id: 'c2',
        name: 'Sell',
        category: 'core',
        groupName: 'Cadena Principal',
        sequenceOrder: 2,
        health: 4,
        importance: 5,
        feasibility: 4,
        labelPosition: 'top',
        visible: true,
        profile: {
          apqcCode: '3.1',
          vision: 'Captar y cerrar oportunidades comerciales maximizando ingresos y margen operativo.',
          processOwner: 'Vicepresidente Comercial',
          customer: 'Compradores B2B y consumidores B2C',
          customerExpectation: 'Asesoría comercial transparente, precios competitivos y agilidad.',
          outcome: 'Órdenes de compra confirmadas y contratos comerciales firmados.',
          trigger: 'Llegada de lead comercial o solicitud de cotización.',
          firstActivity: 'Calificar prospecto y registrar requerimiento.',
          lastActivity: 'Generar orden de venta formal y transferir a despacho.',
          interfacesInbound: 'Innovación y Mercadeo',
          interfacesOutbound: 'Distribución y Entrega (Deliver)',
          requiredResourcesHuman: 'Ejecutivos de cuenta, asesores comerciales.',
          requiredResourcesInfo: 'Catálogo de precios, stock disponible, acuerdos marco.',
          requiredResourcesEnv: 'Sistema CRM comercial y pasarela de cobro.',
          performanceMeasures: 'Tasa de conversión de ventas\nTicket promedio\nCumplimiento de cuota comercial'
        },
        profileEn: {
          apqcCode: '3.1',
          vision: 'Capture and close commercial opportunities while maximizing revenue and gross margin.',
          processOwner: 'Vice President of Sales',
          customer: 'B2B buyers and B2C consumers',
          customerExpectation: 'Transparent commercial advice, competitive pricing, and swift execution.',
          outcome: 'Confirmed sales orders and signed commercial contracts.',
          trigger: 'Incoming sales inquiry or quotation request.',
          firstActivity: 'Qualify lead and capture client requirements.',
          lastActivity: 'Issue formal sales order and route to fulfillment.',
          interfacesInbound: 'Innovation and Marketing',
          interfacesOutbound: 'Deliver / Fulfillment',
          requiredResourcesHuman: 'Account executives, sales representatives.',
          requiredResourcesInfo: 'Pricing catalogue, available inventory, credit terms.',
          requiredResourcesEnv: 'Sales CRM platform and payment gateway.',
          performanceMeasures: 'Sales conversion rate\nAverage order value (AOV)\nSales quota attainment %'
        }
      },
      {
        id: 'c3',
        name: 'Deliver',
        category: 'core',
        groupName: 'Cadena Principal',
        sequenceOrder: 3,
        health: 5,
        importance: 4,
        feasibility: 2,
        labelPosition: 'right',
        visible: true,
        profile: {
          apqcCode: '4.4',
          vision: 'Garantizar el despacho, transporte y entrega puntual de pedidos con cero defectos.',
          processOwner: 'Director de Logística y Operaciones',
          customer: 'Cliente receptor del pedido',
          customerExpectation: 'Entrega a tiempo (OTIF), empaque en perfecto estado y trazabilidad.',
          outcome: 'Mercancía entregada a satisfacción y guía de remisión firmada.',
          trigger: 'Recepción de orden de pedido aprobada.',
          firstActivity: 'Programar picking y empaque en centro de distribución.',
          lastActivity: 'Entregar producto en destino y registrar firma de recepción.',
          interfacesInbound: 'Ventas (Sell)',
          interfacesOutbound: 'Facturación y Servicio al Cliente',
          requiredResourcesHuman: 'Operadores logísticos, despachadores, transportistas.',
          requiredResourcesInfo: 'Guía de despacho, dirección de entrega, ruta óptima.',
          requiredResourcesEnv: 'Sistema de Gestión de Almacenes (WMS) y flota de transporte.',
          performanceMeasures: 'On-Time In-Full (OTIF) %\nCosto logístico por pedido\nTasa de incidencias en transporte'
        },
        profileEn: {
          apqcCode: '4.4',
          vision: 'Ensure prompt order fulfillment, dispatch, and delivery with zero defects.',
          processOwner: 'Director of Logistics and Supply Chain',
          customer: 'Receiving customer / client',
          customerExpectation: 'On-time delivery (OTIF), undamaged packaging, and tracking visibility.',
          outcome: 'Products delivered successfully with signed proof of delivery.',
          trigger: 'Receipt of confirmed customer sales order.',
          firstActivity: 'Schedule warehouse picking and packing.',
          lastActivity: 'Deliver goods to customer destination and obtain signed receipt.',
          interfacesInbound: 'Sales (Sell)',
          interfacesOutbound: 'Invoicing & Customer Support',
          requiredResourcesHuman: 'Warehouse operators, dispatchers, drivers.',
          requiredResourcesInfo: 'Packing list, delivery address, optimized route manifest.',
          requiredResourcesEnv: 'Warehouse Management System (WMS) and transport fleet.',
          performanceMeasures: 'On-Time In-Full (OTIF) %\nLogistics cost per delivery\nTransit damage rate'
        }
      },
      { id: 's1', name: 'Attract, Develop, and Retain Workforce', category: 'support', health: 3, importance: 3, feasibility: 4, labelPosition: 'bottom', visible: true },
      { id: 's2', name: 'Workplace and Infrastructure Provision', category: 'support', health: 2, importance: 3, feasibility: 5, labelPosition: 'bottom', visible: true },
      {
        id: 's3',
        name: 'Procure to Pay',
        category: 'support',
        health: 4,
        importance: 4,
        feasibility: 3,
        labelPosition: 'bottom',
        visible: true,
        profile: {
          apqcCode: '4.2',
          vision: 'Garantizar el abastecimiento oportuno y eficiente de bienes y servicios cumpliendo los estándares de calidad.',
          processOwner: 'Director de Compras / CFO',
          customer: 'Unidades solicitantes de la organización',
          customerExpectation: 'Abastecimiento oportuno, precios económicos y especificaciones completas.',
          outcome: 'Bienes o servicios provistos y factura pagada al proveedor.',
          trigger: 'Identificación y aprobación de requerimiento de compra.',
          firstActivity: 'Registrar solicitud de compra (Requisición).',
          lastActivity: 'Emitir orden de compra formal y tramitar pago de factura.',
          interfacesInbound: 'Planificación de Compras',
          interfacesOutbound: 'Cuentas por Pagar y Ejecución de Obra',
          requiredResourcesHuman: 'Compradores, ingenieros de planta, aprobadores.',
          requiredResourcesInfo: 'Pautas de compras, evaluación de proveedores, contratos marco.',
          requiredResourcesEnv: 'Módulo de Compras del ERP.',
          performanceMeasures: 'Tiempo de ciclo de compra\nCostos operativos de adquisición\nTasa de errores en órdenes'
        },
        profileEn: {
          apqcCode: '4.2',
          vision: 'The objective of the procurement process is to secure that the entire range of external products and services becomes available on time and is at the required level of quality.',
          processOwner: 'Chief Financial Officer (CFO)',
          customer: 'Requesting unit',
          customerExpectation: 'Timely, economic and complete provision',
          outcome: 'Delivered products or provided services for the requested unit',
          trigger: 'Need is identified',
          firstActivity: 'Submit Request',
          lastActivity: 'Create Purchase Order',
          interfacesInbound: 'Plan-to-Procure',
          interfacesOutbound: 'Construct-to-Complete',
          requiredResourcesHuman: 'Site Engineer, Clerk, Works Engineer',
          requiredResourcesInfo: 'procurement guidelines, supplier rating, framework contract',
          requiredResourcesEnv: 'Procurement information system',
          performanceMeasures: 'Cycle Time\nOperational Costs\nError Rate'
        }
      },
      { id: 's4', name: 'Corporate Finance and Operational Compliance', category: 'support', health: 4, importance: 4, feasibility: 2, labelPosition: 'bottom', visible: true },
      { id: 's5', name: 'Shareholder and Stakeholder Management', category: 'support', health: 3, importance: 3, feasibility: 4, labelPosition: 'bottom', visible: true },
    ]
  },
  {
    id: 'dumas-medio',
    name: 'Ingeniería y Consultoría',
    description: 'Operación con grupos en Core: Contract Acquisition y Contract Execution.',
    company: {
      name: 'Engineering & Services Partner',
      industry: 'Servicios Profesionales de Ingeniería',
      description: 'Consultoría e ingeniería por contratos públicos y privados.'
    },
    processes: [
      { id: 'mm1', name: 'Develop Vision and Strategy', category: 'management', health: 4, importance: 5, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'mm2', name: 'Develop and Manage Services', category: 'management', health: 3, importance: 4, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'mm3', name: 'Manage Business Capabilities', category: 'management', health: 3, importance: 3, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'mm4', name: 'Market and Sell Services', category: 'management', health: 4, importance: 5, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'ca1', name: 'Demand-to-Selection', category: 'core', groupName: 'Contract Acquisition', sequenceOrder: 1, health: 3, importance: 4, feasibility: 3, labelPosition: 'left', visible: true },
      { id: 'ca2', name: 'Selection-to-Bid', category: 'core', groupName: 'Contract Acquisition', sequenceOrder: 2, health: 4, importance: 4, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'ca3', name: 'Approval-to-Contract', category: 'core', groupName: 'Contract Acquisition', sequenceOrder: 3, health: 4, importance: 5, feasibility: 2, labelPosition: 'right', visible: true },
      { id: 'ce1', name: 'Contract-to-Plan', category: 'core', groupName: 'Contract Execution', sequenceOrder: 1, health: 3, importance: 4, feasibility: 4, labelPosition: 'left', visible: true },
      {
        id: 'ce2',
        name: 'Plan-to-Completion',
        category: 'core',
        groupName: 'Contract Execution',
        sequenceOrder: 2,
        health: 4,
        importance: 5,
        feasibility: 3,
        labelPosition: 'top',
        visible: true,
        profile: {
          apqcCode: '4.2.1',
          vision: 'Ejecutar las obras y entregables de consultoría dentro del presupuesto, plazo y calidad acordados.',
          processOwner: 'Director de Operaciones / Jefe de Proyecto',
          customer: 'Cliente contratante',
          customerExpectation: 'Entregables rigurosos, informes de avance periódicos y resolución rápida de cambios.',
          outcome: 'Obras y memorias de cálculo entregadas y aprobadas por la supervisión.',
          trigger: 'Aprobación del plan de trabajo de ingeniería.',
          firstActivity: 'Asignar paquetes de trabajo a las especialidades de ingeniería.',
          lastActivity: 'Entregar expediente final y obtener acta de conformidad.',
          interfacesInbound: 'Planificación de Contratos (Contract-to-Plan)',
          interfacesOutbound: 'Cierre y Liquidación (Completion-to-Expiry)',
          requiredResourcesHuman: 'Ingenieros especialistas, proyectistas BIM, inspectores.',
          requiredResourcesInfo: 'Plan del proyecto, normas técnicas, solicitudes de cambio (RFIs).',
          requiredResourcesEnv: 'Entorno Común de Datos (CDE) y software BIM/CAD.',
          performanceMeasures: 'Índice de desempeño del cronograma (SPI)\nÍndice de desempeño del costo (CPI)\nNúmero de no conformidades técnicas'
        },
        profileEn: {
          apqcCode: '4.2.1',
          vision: 'Execute engineering deliverables and field works within committed budget, timeline, and quality.',
          processOwner: 'Operations Director / Lead Project Manager',
          customer: 'Contracting client / project sponsor',
          customerExpectation: 'Rigorous engineering deliverables, regular progress reports, and swift change handling.',
          outcome: 'Completed engineering works and technical reports accepted by client.',
          trigger: 'Approval of baseline project plan.',
          firstActivity: 'Assign work breakdown packages to engineering discipline leads.',
          lastActivity: 'Submit final documentation and obtain client certificate of completion.',
          interfacesInbound: 'Contract-to-Plan',
          interfacesOutbound: 'Completion-to-Expiry',
          requiredResourcesHuman: 'Discipline lead engineers, BIM modelers, quality inspectors.',
          requiredResourcesInfo: 'Project execution plan, building codes, technical RFIs.',
          requiredResourcesEnv: 'Common Data Environment (CDE) and BIM/CAD modeling tools.',
          performanceMeasures: 'Schedule Performance Index (SPI)\nCost Performance Index (CPI)\nTechnical non-conformance count'
        }
      },
      { id: 'ce3', name: 'Completion-to-Expiry', category: 'core', groupName: 'Contract Execution', sequenceOrder: 3, health: 5, importance: 3, feasibility: 3, labelPosition: 'right', visible: true },
      { id: 'sm1', name: 'Manage Human Capital', category: 'support', health: 3, importance: 3, feasibility: 4, labelPosition: 'bottom', visible: true },
      { id: 'sm2', name: 'Manage IT', category: 'support', health: 4, importance: 4, feasibility: 4, labelPosition: 'bottom', visible: true },
      { id: 'sm3', name: 'Manage Financial Resources', category: 'support', health: 4, importance: 5, feasibility: 3, labelPosition: 'bottom', visible: true },
      { id: 'sm4', name: 'Manage Assets', category: 'support', health: 2, importance: 2, feasibility: 5, labelPosition: 'bottom', visible: true },
      { id: 'sm5', name: 'Manage Risk and Compliance', category: 'support', health: 4, importance: 4, feasibility: 2, labelPosition: 'bottom', visible: true },
      { id: 'sm6', name: 'Manage External Relationships', category: 'support', health: 3, importance: 3, feasibility: 3, labelPosition: 'bottom', visible: true },
    ]
  },
  {
    id: 'dumas-multiple',
    name: 'Operador de Transporte Masivo',
    description: 'Operaciones múltiples integradas: Clientes, Vehículos, Transporte e Infraestructura.',
    company: {
      name: 'Metropolitan Public Transport Authority',
      industry: 'Transporte Público y Movilidad',
      description: 'Gestión integral del transporte público de trenes y autobuses.'
    },
    processes: [
      { id: 'mu1', name: 'Manage Enterprise', category: 'management', health: 4, importance: 5, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'mu2', name: 'Communicate in and out', category: 'management', health: 3, importance: 3, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'mu3', name: 'Manage Processes', category: 'management', health: 4, importance: 4, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'mu4', name: 'Manage Quality', category: 'management', health: 4, importance: 4, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'mu5', name: 'Manage Risks and Opportunities', category: 'management', health: 4, importance: 5, feasibility: 2, labelPosition: 'top', visible: true },
      { id: 'mu6', name: 'Manage Innovation', category: 'management', health: 3, importance: 4, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'crm1', name: 'Contact Customer', category: 'core', groupName: 'Manage Customer Relationship', sequenceOrder: 1, health: 3, importance: 4, feasibility: 4, labelPosition: 'left', visible: true },
      { id: 'crm2', name: 'Manage Sales', category: 'core', groupName: 'Manage Customer Relationship', sequenceOrder: 2, health: 4, importance: 4, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'crm3', name: 'Foster Relationship', category: 'core', groupName: 'Manage Customer Relationship', sequenceOrder: 4, health: 4, importance: 4, feasibility: 4, labelPosition: 'right', visible: true },
      { id: 'veh1', name: 'Plan and Buy Vehicles', category: 'core', groupName: 'Operate Vehicles', sequenceOrder: 1, health: 3, importance: 5, feasibility: 2, labelPosition: 'left', visible: true },
      { id: 'veh2', name: 'Maintain Vehicles', category: 'core', groupName: 'Operate Vehicles', sequenceOrder: 2, health: 4, importance: 5, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'veh3', name: 'Check Vehicles', category: 'core', groupName: 'Operate Vehicles', sequenceOrder: 4, health: 5, importance: 5, feasibility: 4, labelPosition: 'right', visible: true },
      { id: 'tra1', name: 'Plan Customer Transport', category: 'core', groupName: 'Transport Customer', sequenceOrder: 1, health: 4, importance: 5, feasibility: 3, labelPosition: 'left', visible: true },
      { id: 'tra2', name: 'Transport Customer', category: 'core', groupName: 'Transport Customer', sequenceOrder: 3, health: 5, importance: 5, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'tra3', name: 'Evaluate Transport', category: 'core', groupName: 'Transport Customer', sequenceOrder: 4, health: 4, importance: 4, feasibility: 4, labelPosition: 'right', visible: true },
      { id: 'inf1', name: 'Plan Infrastructure', category: 'core', groupName: 'Provide Infrastructure', sequenceOrder: 1, health: 3, importance: 4, feasibility: 3, labelPosition: 'left', visible: true },
      { id: 'inf2', name: 'Build Infrastructure', category: 'core', groupName: 'Provide Infrastructure', sequenceOrder: 2, health: 4, importance: 5, feasibility: 4, labelPosition: 'top', visible: true },
      { id: 'inf3', name: 'Maintain Infrastructure', category: 'core', groupName: 'Provide Infrastructure', sequenceOrder: 3, health: 5, importance: 5, feasibility: 3, labelPosition: 'top', visible: true },
      { id: 'inf4', name: 'Evaluate Infrastructure', category: 'core', groupName: 'Provide Infrastructure', sequenceOrder: 4, health: 4, importance: 4, feasibility: 4, labelPosition: 'right', visible: true },
      { id: 'sup1', name: 'Manage Personnel', category: 'support', health: 3, importance: 4, feasibility: 4, labelPosition: 'bottom', visible: true },
      { id: 'sup2', name: 'Manage Financials', category: 'support', health: 4, importance: 5, feasibility: 3, labelPosition: 'bottom', visible: true },
      { id: 'sup3', name: 'Manage Information', category: 'support', health: 3, importance: 4, feasibility: 3, labelPosition: 'bottom', visible: true },
      { id: 'sup4', name: 'Manage Materials', category: 'support', health: 4, importance: 3, feasibility: 4, labelPosition: 'bottom', visible: true },
      { id: 'sup5', name: 'Manage Disruptions', category: 'support', health: 3, importance: 5, feasibility: 2, labelPosition: 'bottom', visible: true },
      { id: 'sup6', name: 'Provide Winter Service', category: 'support', health: 3, importance: 4, feasibility: 3, labelPosition: 'bottom', visible: true },
    ]
  }
];
